### PR TITLE
Adding a more thorough explanation of the isValid function

### PR DESCRIPTION
**Pull request by OmarOmeiri**

### CODE REVIEW

**Comment by OmarOmeiri** [comment]
As [PR - 1859](https://github.com/iamkun/dayjs/pull/1859) of [iamkun/dayjs](https://github.com/iamkun/dayjs)

**Comment by OmarOmeiri** [comment]
As [PR - 1859](https://github.com/iamkun/dayjs/pull/1859) of []https://github.com/iamkun/dayjs

**Comment by iamkun** [comment]
Thanks. 

Can we combine browser and node.js into one, since there's no difference between them?

Also, please keep the tip in the node.js part that strict parsing needs a plugin.

**Comment by OmarOmeiri** [comment]
Done!

**Pull request merged**
