### PR TITLE
Updated Duration documentation

### PR DESCRIPTION
**Pull request by stebogit**
Should you merge https://github.com/iamkun/dayjs/pull/1099 😜

### CODE REVIEW

**Comment by iamkun** [comment]
I prefer not to add this to the docs. It's a little wired syntax I think. 🤔

**Comment by stebogit** [comment]
You mean the way I phrased it or the actual new option?

**Comment by iamkun** [comment]
I think we should not tell our new user that we could add a duration directly. 

And adding this feature is only for migration from moment.js.

**Comment by stebogit** [comment]
But if it is not in the docs, how would people migrating from moment learn this is available?
Is there a "how to migrate from moment" document maybe?

**Comment by iamkun** [comment]
Cause moment support this, so we implement this. But this does not mean we should encourage our users to use this syntax. 

I think a clear way for most users is to convert duration to milliseconds by our user and to added to the Dayjs instance.

**Comment by iamkun** [comment]
I'll close this since it's been a while since it's been opened. Feel free to reopen if you have updates on this

**Pull request closed without merging**
